image: openjdk:11

stages:
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

distribution:
  stage: publish
  script:
    - ./gradlew distZip
  artifacts:
    paths:
      - build/distributions/pico*.zip
    expire_in: 1 week

